### ISSUE TITLE
Bug report of format chainspec file to raw format

### ISSUE THREAD

**Issue by ff13dfly** [paritytech/subport#286]
Hi, team.

There is a message asking me to report the bug when I tried to start my private blockchain netwok. 

The message as follow:
--------------------------------start of message------------------------------------
```
Version: 3.0.0-dev-a8117ad-x86_64-macos

   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: sp_panic_handler::set::{{closure}}
   3: std::panicking::rust_panic_with_hook
             at /rustc/5d04957a4b4714f71d38326fc96a0b0ef6dc5800/library/std/src/panicking.rs:595:17
   4: std::panicking::begin_panic::{{closure}}
   5: std::sys_common::backtrace::__rust_end_short_backtrace
   6: std::panicking::begin_panic
   7: pallet_babe::<impl pallet_babe::pallet::Pallet<T>>::initialize_authorities
   8: <(TupleElement0,TupleElement1,TupleElement2,TupleElement3) as pallet_session::SessionHandler<AId>>::on_genesis_session
   9: std::thread::local::LocalKey<T>::with
  10: sp_state_machine::basic::BasicExternalities::execute_with_storage
  11: <node_runtime::GenesisConfig as sp_runtime::BuildStorage>::assimilate_storage
  12: sp_runtime::BuildStorage::build_storage
  13: <sc_chain_spec::chain_spec::ChainSpec<G,E> as sc_chain_spec::ChainSpec>::as_json
  14: sc_service::chain_ops::import_blocks::build_spec
  15: sc_cli::commands::build_spec_cmd::BuildSpecCmd::run
  16: sc_cli::runner::Runner<C>::sync_run
  17: node_cli::command::run
  18: substrate::main
  19: std::sys_common::backtrace::__rust_begin_short_backtrace
  20: std::rt::lang_start::{{closure}}
  21: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/5d04957a4b4714f71d38326fc96a0b0ef6dc5800/library/core/src/ops/function.rs:259:13
      std::panicking::try::do_call
             at /rustc/5d04957a4b4714f71d38326fc96a0b0ef6dc5800/library/std/src/panicking.rs:379:40
      std::panicking::try
             at /rustc/5d04957a4b4714f71d38326fc96a0b0ef6dc5800/library/std/src/panicking.rs:343:19
      std::panic::catch_unwind
             at /rustc/5d04957a4b4714f71d38326fc96a0b0ef6dc5800/library/std/src/panic.rs:431:14
      std::rt::lang_start_internal
             at /rustc/5d04957a4b4714f71d38326fc96a0b0ef6dc5800/library/std/src/rt.rs:51:25
  22: _main


Thread 'main' panicked at 'Authorities are already initialized!', /Users/fuzhongqiang/Desktop/www/Anchor/frame/babe/src/lib.rs:734
```
--------------------------------end of message------------------------------------

Hope to help.

Best regard.
Fuu

**Comment by NukeManDan** [comment]
Sorry for the delay in reply!
`Thread 'main' panicked at 'Authorities are already initialized!'` should hint at your issue. Did you follow the instructions here? https://docs.substrate.io/tutorials/v3/private-network/

If you move through this and still get errors, please let me know here and I am very happy to assist further with a https://stackoverflow.com/help/minimal-reproducible-example :grin:
