### ISSUE TITLE
Impossible to structure runtime

### ISSUE THREAD

**Issue by vporton** [paritytech/subport#49]
I apply this patch to `substrate` v2.0.0:

```patch
diff --git a/primitives/io/src/lib.rs b/primitives/io/src/lib.rs
index 382a0c4b3..a3fe0544b 100644
--- a/primitives/io/src/lib.rs
+++ b/primitives/io/src/lib.rs
@@ -89,12 +89,7 @@ pub trait Storage {
                self.storage(key).map(|s| s.to_vec())
        }

-       /// Get `key` from storage, placing the value into `value_out` and return the number of
-       /// bytes that the entry in storage has beyond the offset or `None` if the storage entry
-       /// doesn't exist at all.
-       /// If `value_out` length is smaller than the returned length, only `value_out` length bytes
-       /// are copied into `value_out`.
-       fn read(&self, key: &[u8], value_out: &mut [u8], value_offset: u32) -> Option<u32> {
+       fn read_impl(&self, key: &[u8], value_out: &mut [u8], value_offset: u32) -> Option<u32> {
                self.storage(key).map(|value| {
                        let value_offset = value_offset as usize;
                        let data = &value[value_offset.min(value.len())..];
@@ -102,6 +97,16 @@ pub trait Storage {
                        value_out[..written].copy_from_slice(&data[..written]);
                        data.len() as u32
                })
+
+       }
+
+       /// Get `key` from storage, placing the value into `value_out` and return the number of
+       /// bytes that the entry in storage has beyond the offset or `None` if the storage entry
+       /// doesn't exist at all.
+       /// If `value_out` length is smaller than the returned length, only `value_out` length bytes
+       /// are copied into `value_out`.
+       fn read(&self, key: &[u8], value_out: &mut [u8], value_offset: u32) -> Option<u32> {
+               self.read_impl(key, value_out, value_offset)
        }

        /// Set `key` to `value` in the storage.
```

After this it does not compile:

```
error[E0599]: no method named `read_impl` found for reference `&&mut dyn storage::proc_macro_runtime_interface::Externalities` in the current scope
   --> primitives/io/src/lib.rs:109:8
    |
109 |         self.read_impl(key, value_out, value_offset)
    |              ^^^^^^^^^ method not found in `&&mut dyn storage::proc_macro_runtime_interface::Externalities`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `sp-io`

To learn more, run the command again with --verbose.
```

Then I try another way:
```patch
diff --git a/primitives/io/src/lib.rs b/primitives/io/src/lib.rs
index 382a0c4b3..a3fe0544b 100644
--- a/primitives/io/src/lib.rs
+++ b/primitives/io/src/lib.rs
@@ -89,12 +89,7 @@ pub trait Storage {
                self.storage(key).map(|s| s.to_vec())
        }

-       /// Get `key` from storage, placing the value into `value_out` and return the number of
-       /// bytes that the entry in storage has beyond the offset or `None` if the storage entry
-       /// doesn't exist at all.
-       /// If `value_out` length is smaller than the returned length, only `value_out` length bytes
-       /// are copied into `value_out`.
-       fn read(&self, key: &[u8], value_out: &mut [u8], value_offset: u32) -> Option<u32> {
+       fn read_impl(&self, key: &[u8], value_out: &mut [u8], value_offset: u32) -> Option<u32> {
                self.storage(key).map(|value| {
                        let value_offset = value_offset as usize;
                        let data = &value[value_offset.min(value.len())..];
@@ -102,6 +97,16 @@ pub trait Storage {
                        value_out[..written].copy_from_slice(&data[..written]);
                        data.len() as u32
                })
+
+       }
+
+       /// Get `key` from storage, placing the value into `value_out` and return the number of
+       /// bytes that the entry in storage has beyond the offset or `None` if the storage entry
+       /// doesn't exist at all.
+       /// If `value_out` length is smaller than the returned length, only `value_out` length bytes
+       /// are copied into `value_out`.
+       fn read(&self, key: &[u8], value_out: &mut [u8], value_offset: u32) -> Option<u32> {
+               storage::read_impl(key, value_out, value_offset)
        }

        /// Set `key` to `value` in the storage.
```
It compiles but fails the tests:
```
---- storage::types::value::test::test stdout ----
thread 'storage::types::value::test::test' panicked at 'already borrowed: BorrowMutError', /home/porton/.cargo/registry/src/github.com-1ecc6299db9ec823/environmental-1.1.2/src/lib.rs:143:41

---- storage::types::map::test::test stdout ----
thread 'storage::types::map::test::test' panicked at 'already borrowed: BorrowMutError', /home/porton/.cargo/registry/src/github.com-1ecc6299db9ec823/environmental-1.1.2/src/lib.rs:143:41

---- storage::types::double_map::test::test stdout ----
thread 'storage::types::double_map::test::test' panicked at 'already borrowed: BorrowMutError', /home/porton/.cargo/registry/src/github.com-1ecc6299db9ec823/environmental-1.1.2/src/lib.rs:143:41
```

This example shows that there is no (at least obvious) way to extract a part of a runtime function into a separate function (what may be necessary to factor out code of two similar functions into a third function). That's bad. What to do now?

**Comment by danforbes** [comment]
I believe that if you create a free-standing function it would not have a `self`.

**Comment by vporton** [comment]
> I believe that if you create a free-standing function it would not have a `self`.

If it has no `self` then _what_ should be in the place of `self` in `self.read_impl(key, value_out, value_offset)` of the example?

**Comment by danforbes** [comment]
A free-standing function is not called "on" some instance of an object. So assuming the function was imported as `read_impl` you would just invoke it as `read_impl(key, value_out, value_offset)`...perhaps if you need to access some member variable of an object (like a storage map), you could just add it to the signature of the free-standing function.

**Comment by vporton** [comment]
> A free-standing function is not called "on" some instance of an object. So assuming the function was imported as `read_impl` you would just invoke it as `read_impl(key, value_out, value_offset)`...perhaps if you need to access some member variable of an object (like a storage map), you could just add it to the signature of the free-standing function.

Here is what you suggest to do:
```rust
	fn read_impl(key: &[u8], value_out: &mut [u8], value_offset: u32) -> Option<u32> {
		self.storage(key).map(|value| {
			let value_offset = value_offset as usize;
			let data = &value[value_offset.min(value.len())..];
			let written = std::cmp::min(data.len(), value_out.len());
			value_out[..written].copy_from_slice(&data[..written]);
			data.len() as u32
		})

	}
```
Compilation of this function would fail because it does use `self` without having the argument `self`!

I need to call `storage()` inside `read_impl` _not_ "access some member variable of an object".

**Comment by bkchr** [comment]
Maybe you should start by reading the docs https://docs.rs/sp-runtime-interface/2.0.0/sp_runtime_interface/attr.runtime_interface.html

There you see that self is a `&mut dyn Externalities`.

However, I'm still not sure what you are trying to do there? Could you explain what you want to achieve exactly?

**Comment by vporton** [comment]
> There you see that self is a `&mut dyn Externalities`.

OK, now it works. I am closing the issue.
