### ISSUE TITLE
RPC failed to get accountNextIndex

### ISSUE THREAD

**Issue by RainFallsSilent** [paritytech/subport#89]
my code:
```javascript
  const keyring = new Keyring({ type: 'sr25519' })
  const alice = keyring.addFromUri('//Alice', { name: 'Alice default' })
  const nonce = await api.rpc.system.accountNextIndex(alice);
  console.log("nonce:", nonce.toString());
```

from https://polkadot.js.org/docs/api/cookbook/tx/ , the sample is :
```javascript
  // retrieve sender's next index/nonce, taking txs in the pool into account
  const nonce = await api.rpc.system.accountNextIndex(sender);

  // send, just retrieving the hash, not waiting on status
  const txhash = await api.tx.balances
    .transfer(recipient, 123)
    .signAndSend(sender, { nonce });
```

I tested the method and got the error:
```
2021-01-29 00:59:19        RPC-CORE: accountNextIndex(accountId: AccountId): Index:: createType(AccountId):: Unknown type passed to AccountId constructor
(node:29677) UnhandledPromiseRejectionWarning: Error: createType(AccountId):: Unknown type passed to AccountId constructor
    at createTypeUnsafe (/Users/jiangzehua/work/elastos/src/github.com/tearust/tea-layer1-facade/node_modules/@polkadot/types/create/createType.js:68:11)
    at inputs.map (/Users/jiangzehua/work/elastos/src/github.com/tearust/tea-layer1-facade/node_modules/@polkadot/rpc-core/index.js:373:69)
    at Array.map (<anonymous>)
    at Rpc._formatInputs (/Users/jiangzehua/work/elastos/src/github.com/tearust/tea-layer1-facade/node_modules/@polkadot/rpc-core/index.js:373:19)
    at callWithRegistry (/Users/jiangzehua/work/elastos/src/github.com/tearust/tea-layer1-facade/node_modules/@polkadot/rpc-core/index.js:246:27)
    at Observable._rxjs.Observable.observer [as _subscribe] (/Users/jiangzehua/work/elastos/src/github.com/tearust/tea-layer1-facade/node_modules/@polkadot/rpc-core/index.js:255:9)
    at Observable._trySubscribe (/Users/jiangzehua/work/elastos/src/github.com/tearust/tea-layer1-facade/node_modules/@polkadot/rpc-core/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/Users/jiangzehua/work/elastos/src/github.com/tearust/tea-layer1-facade/node_modules/@polkadot/rpc-core/node_modules/rxjs/internal/Observable.js:30:22)
    at Observable.ConnectableObservable.connect (/Users/jiangzehua/work/elastos/src/github.com/tearust/tea-layer1-facade/node_modules/@polkadot/rpc-core/node_modules/rxjs/internal/observable/ConnectableObservable.js:47:18)
    at RefCountOperator.call (/Users/jiangzehua/work/elastos/src/github.com/tearust/tea-layer1-facade/node_modules/@polkadot/rpc-core/node_modules/rxjs/internal/operators/refCount.js:33:49)
(node:29677) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:29677) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I tried to add ```AccountId: '[u8; 32]'``` to types: 
```javascript
const api = await ApiPromise.create({
    types,
    rpc,
  })
```
but not solved the problem, the error is:
```
2021-01-29 01:26:57        RPC-CORE: accountNextIndex(accountId: AccountId): Index:: createType(AccountId):: value.subarray is not a function
(node:30980) UnhandledPromiseRejectionWarning: Error: createType(AccountId):: value.subarray is not a function
    at createTypeUnsafe (/Users/jiangzehua/work/elastos/src/github.com/tearust/tea-layer1-facade/node_modules/@polkadot/types/create/createType.js:68:11)
    at inputs.map (/Users/jiangzehua/work/elastos/src/github.com/tearust/tea-layer1-facade/node_modules/@polkadot/rpc-core/index.js:373:69)
    at Array.map (<anonymous>)
    at Rpc._formatInputs (/Users/jiangzehua/work/elastos/src/github.com/tearust/tea-layer1-facade/node_modules/@polkadot/rpc-core/index.js:373:19)
    at callWithRegistry (/Users/jiangzehua/work/elastos/src/github.com/tearust/tea-layer1-facade/node_modules/@polkadot/rpc-core/index.js:246:27)
    at Observable._rxjs.Observable.observer [as _subscribe] (/Users/jiangzehua/work/elastos/src/github.com/tearust/tea-layer1-facade/node_modules/@polkadot/rpc-core/index.js:255:9)
    at Observable._trySubscribe (/Users/jiangzehua/work/elastos/src/github.com/tearust/tea-layer1-facade/node_modules/@polkadot/rpc-core/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/Users/jiangzehua/work/elastos/src/github.com/tearust/tea-layer1-facade/node_modules/@polkadot/rpc-core/node_modules/rxjs/internal/Observable.js:30:22)
    at Observable.ConnectableObservable.connect (/Users/jiangzehua/work/elastos/src/github.com/tearust/tea-layer1-facade/node_modules/@polkadot/rpc-core/node_modules/rxjs/internal/observable/ConnectableObservable.js:47:18)
    at RefCountOperator.call (/Users/jiangzehua/work/elastos/src/github.com/tearust/tea-layer1-facade/node_modules/@polkadot/rpc-core/node_modules/rxjs/internal/operators/refCount.js:33:49)
(node:30980) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:30980) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Then I tried to use ```AccountId``` of polkadot/types:
```javascript
const { AccountId } = require('@polkadot/types/interfaces')
...
const keyring = new Keyring({ type: 'sr25519' })
const alice = keyring.addFromUri('//Alice', { name: 'Alice default' })
const nonce = await api.rpc.system.accountNextIndex<AccountId>(alice);
``` 
the value of ```nonce``` is always false.

I'm not sure if this is a bug of rpc ```accountNextIndex```？

**Comment by al3mart** [comment]
What you are doing with this line

```
const alice = keyring.addFromUri('//Alice', { name: 'Alice default' })
```

Is loading the keypair for that account, but that is not what you are looking for in this case, the address is just enough.
So, the folowwing should work

```
const alice = keyring.addFromUri('//Alice', { name: 'Alice default' }).address;
```

Instead, for signing you want to use the keypair

I am not an expert on polkadot.js but I think that works as I said. Will be happy if someone correct me if wrong :)

**Comment by NukeManDan** [comment]
hey @RainFallsSilent is this issue still relevant? Did you find an answer that you can share here in this issue thread for people searching in the future?

I am going to close this one, and please do reopen if you need further help 🙏🏼
